# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeeffb35dddc0cd5c00704ad0b0f4601cb8f42a455b233da40154774e1871e48f11dd0dd661950dca224ba30dc8224097a8c84b1bfdc837ab2ac55b3b21ccc56

test:
  secret_key_base: 6675d920ea5020140d77fbb3039e0a577dc4d63fa588d21ac8df22433b06e06e8d8fb09d03b9ee4a99c525a2ae0e9fc83c68f3243504ef8c79f3b709e2a73a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
